// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/0xsoniclabs/norma/driver/network (interfaces: Host)
//
// Generated by this command:
//
//	mockgen -destination host_mock.go -package network . Host
//

// Package network is a generated GoMock package.
package network

import (
	context "context"
	io "io"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockHost is a mock of Host interface.
type MockHost struct {
	ctrl     *gomock.Controller
	recorder *MockHostMockRecorder
	isgomock struct{}
}

// MockHostMockRecorder is the mock recorder for MockHost.
type MockHostMockRecorder struct {
	mock *MockHost
}

// NewMockHost creates a new mock instance.
func NewMockHost(ctrl *gomock.Controller) *MockHost {
	mock := &MockHost{ctrl: ctrl}
	mock.recorder = &MockHostMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHost) EXPECT() *MockHostMockRecorder {
	return m.recorder
}

// CheckRunning mocks base method.
func (m *MockHost) CheckRunning(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckRunning", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// CheckRunning indicates an expected call of CheckRunning.
func (mr *MockHostMockRecorder) CheckRunning(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckRunning", reflect.TypeOf((*MockHost)(nil).CheckRunning), ctx)
}

// Cleanup mocks base method.
func (m *MockHost) Cleanup(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Cleanup", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Cleanup indicates an expected call of Cleanup.
func (mr *MockHostMockRecorder) Cleanup(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Cleanup", reflect.TypeOf((*MockHost)(nil).Cleanup), ctx)
}

// ExecWithEnv mocks base method.
func (m *MockHost) ExecWithEnv(ctx context.Context, cmd, env []string, logName string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExecWithEnv", ctx, cmd, env, logName)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExecWithEnv indicates an expected call of ExecWithEnv.
func (mr *MockHostMockRecorder) ExecWithEnv(ctx, cmd, env, logName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecWithEnv", reflect.TypeOf((*MockHost)(nil).ExecWithEnv), ctx, cmd, env, logName)
}

// GetAddressForService mocks base method.
func (m *MockHost) GetAddressForService(arg0 *ServiceDescription) (*AddressPort, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAddressForService", arg0)
	ret0, _ := ret[0].(*AddressPort)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAddressForService indicates an expected call of GetAddressForService.
func (mr *MockHostMockRecorder) GetAddressForService(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAddressForService", reflect.TypeOf((*MockHost)(nil).GetAddressForService), arg0)
}

// Hostname mocks base method.
func (m *MockHost) Hostname() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Hostname")
	ret0, _ := ret[0].(string)
	return ret0
}

// Hostname indicates an expected call of Hostname.
func (mr *MockHostMockRecorder) Hostname() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Hostname", reflect.TypeOf((*MockHost)(nil).Hostname))
}

// IsRunning mocks base method.
func (m *MockHost) IsRunning() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsRunning")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsRunning indicates an expected call of IsRunning.
func (mr *MockHostMockRecorder) IsRunning() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsRunning", reflect.TypeOf((*MockHost)(nil).IsRunning))
}

// SaveLogTo mocks base method.
func (m *MockHost) SaveLogTo(ctx context.Context, directory string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveLogTo", ctx, directory)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveLogTo indicates an expected call of SaveLogTo.
func (mr *MockHostMockRecorder) SaveLogTo(ctx, directory any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveLogTo", reflect.TypeOf((*MockHost)(nil).SaveLogTo), ctx, directory)
}

// Stop mocks base method.
func (m *MockHost) Stop(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stop", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Stop indicates an expected call of Stop.
func (mr *MockHostMockRecorder) Stop(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockHost)(nil).Stop), ctx)
}

// StreamLog mocks base method.
func (m *MockHost) StreamLog(ctx context.Context) (io.ReadCloser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StreamLog", ctx)
	ret0, _ := ret[0].(io.ReadCloser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StreamLog indicates an expected call of StreamLog.
func (mr *MockHostMockRecorder) StreamLog(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StreamLog", reflect.TypeOf((*MockHost)(nil).StreamLog), ctx)
}
