// Copyright 2024 Fantom Foundation
// This file is part of Norma System Testing Infrastructure for Sonic.
//
// Norma is free software: you can redistribute it and/or modify
// it under the terms of the GNU Lesser General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Norma is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU lesser General Public License for more details.
//
// You should have received a copy of the GNU Lesser General Public License
// along with Norma. If not, see <http://www.gnu.org/licenses/>.

package app

import (
	"context"
	"crypto/ecdsa"
	"encoding/binary"
	"fmt"
	"math/big"
	"sync/atomic"

	"github.com/0xsoniclabs/norma/driver/rpc"
	"github.com/ethereum/go-ethereum/common"
	"github.com/ethereum/go-ethereum/crypto"
)

// AccountFactory generates any amount of accounts.
// Any factory using the same feederId and appId produces the same sequence of accounts,
// which can be used to reuse existing accounts from previous runs.
type AccountFactory struct {
	chainID         atomic.Pointer[big.Int]
	numAccounts     int64
	feederId, appId uint32
}

// NewAccountFactory creates a new AccountFactory, generating accounts for given feeder and app.
// Re-creating a factory using the same feederId and appId will produce the same sequence of accounts.
// The chain ID the accounts sign for is read from the network on first use.
func NewAccountFactory(feederId, appId uint32) *AccountFactory {
	return &AccountFactory{
		feederId: feederId,
		appId:    appId,
	}
}

// CreateAccount generates the next account in the sequence generated by the AccountFactory.
// The account is initialized with the latest nonce from the RPC.
func (f *AccountFactory) CreateAccount(rpcClient rpc.Client) (*Account, error) {
	id := atomic.AddInt64(&f.numAccounts, 1)
	d := make([]byte, 32)
	binary.BigEndian.PutUint64(d[:24], uint64(id))
	binary.BigEndian.PutUint32(d[24:], f.feederId)
	binary.BigEndian.PutUint32(d[28:], f.appId)
	privateKey, err := crypto.ToECDSA(d)
	if err != nil {
		return nil, err
	}
	address := crypto.PubkeyToAddress(privateKey.PublicKey)

	chainID, err := f.getChainID(rpcClient)
	if err != nil {
		return nil, err
	}

	nonce, err := rpcClient.PendingNonceAt(context.Background(), address)
	if err != nil {
		return nil, fmt.Errorf("failed to get address nonce; %v", err)
	}

	return &Account{
		privateKey: privateKey,
		address:    address,
		chainID:    chainID,
		nonce:      nonce,
	}, nil
}

// getChainID returns the chain ID of the network, reading it from the given client
// the first time it is needed.
func (f *AccountFactory) getChainID(rpcClient rpc.Client) (*big.Int, error) {
	if chainID := f.chainID.Load(); chainID != nil {
		return chainID, nil
	}
	chainID, err := rpcClient.ChainID(context.Background())
	if err != nil {
		return nil, fmt.Errorf("failed to get chain ID; %w", err)
	}
	f.chainID.Store(chainID)
	return chainID, nil
}

// Account represents an account from which we can send transactions.
// It sustains the nonce value - it allows multiple generators which use one Account
// to produce multiple txs in one block.
type Account struct {
	id         int
	privateKey *ecdsa.PrivateKey
	address    common.Address
	chainID    *big.Int
	nonce      uint64
}

// NewAccount creates an Account instance from the provided private key
func NewAccount(id int, privateKeyHex string, chainID int64) (*Account, error) {
	privateKey, err := crypto.HexToECDSA(privateKeyHex)
	if err != nil {
		return nil, err
	}
	address := crypto.PubkeyToAddress(privateKey.PublicKey)
	return &Account{
		id:         id,
		privateKey: privateKey,
		address:    address,
		chainID:    big.NewInt(chainID),
		nonce:      0,
	}, nil
}

// getNextNonce provides a nonce to be used for next transactions sent using this account, with incrementing
func (a *Account) getNextNonce() uint64 {
	current := atomic.AddUint64(&a.nonce, 1)
	return current - 1
}

// getCurrentNonce provides the nonce the next transaction of this account will
// use, without consuming it. It is used for transactions that are expected to be
// rejected by the network and therefore never consume a nonce.
func (a *Account) getCurrentNonce() uint64 {
	return atomic.LoadUint64(&a.nonce)
}
