// Code generated by MockGen. DO NOT EDIT.
// Source: generator.go
//
// Generated by this command:
//
//	mockgen -source generator.go -destination generator_mock.go -package app
//

// Package app is a generated GoMock package.
package app

import (
	reflect "reflect"

	types "github.com/ethereum/go-ethereum/core/types"
	gomock "go.uber.org/mock/gomock"
)

// MockGenerator is a mock of Generator interface.
type MockGenerator struct {
	ctrl     *gomock.Controller
	recorder *MockGeneratorMockRecorder
	isgomock struct{}
}

// MockGeneratorMockRecorder is the mock recorder for MockGenerator.
type MockGeneratorMockRecorder struct {
	mock *MockGenerator
}

// NewMockGenerator creates a new mock instance.
func NewMockGenerator(ctrl *gomock.Controller) *MockGenerator {
	mock := &MockGenerator{ctrl: ctrl}
	mock.recorder = &MockGeneratorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGenerator) EXPECT() *MockGeneratorMockRecorder {
	return m.recorder
}

// Call mocks base method.
func (m *MockGenerator) Call(user int) (Call, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Call", user)
	ret0, _ := ret[0].(Call)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Call indicates an expected call of Call.
func (mr *MockGeneratorMockRecorder) Call(user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Call", reflect.TypeOf((*MockGenerator)(nil).Call), user)
}

// Check mocks base method.
func (m *MockGenerator) Check(ctxt AppContext, call Call, receipt *types.Receipt) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Check", ctxt, call, receipt)
	ret0, _ := ret[0].(error)
	return ret0
}

// Check indicates an expected call of Check.
func (mr *MockGeneratorMockRecorder) Check(ctxt, call, receipt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Check", reflect.TypeOf((*MockGenerator)(nil).Check), ctxt, call, receipt)
}

// Deploy mocks base method.
func (m *MockGenerator) Deploy(ctxt AppContext, numUsers int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Deploy", ctxt, numUsers)
	ret0, _ := ret[0].(error)
	return ret0
}

// Deploy indicates an expected call of Deploy.
func (mr *MockGeneratorMockRecorder) Deploy(ctxt, numUsers any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Deploy", reflect.TypeOf((*MockGenerator)(nil).Deploy), ctxt, numUsers)
}
