// Code generated by MockGen. DO NOT EDIT.
// Source: validator_registry.go
//
// Generated by this command:
//
//	mockgen -source validator_registry.go -destination validator_registry_mock.go -package executor
//

// Package executor is a generated GoMock package.
package executor

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockvalidatorRegistry is a mock of validatorRegistry interface.
type MockvalidatorRegistry struct {
	ctrl     *gomock.Controller
	recorder *MockvalidatorRegistryMockRecorder
	isgomock struct{}
}

// MockvalidatorRegistryMockRecorder is the mock recorder for MockvalidatorRegistry.
type MockvalidatorRegistryMockRecorder struct {
	mock *MockvalidatorRegistry
}

// NewMockvalidatorRegistry creates a new mock instance.
func NewMockvalidatorRegistry(ctrl *gomock.Controller) *MockvalidatorRegistry {
	mock := &MockvalidatorRegistry{ctrl: ctrl}
	mock.recorder = &MockvalidatorRegistryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockvalidatorRegistry) EXPECT() *MockvalidatorRegistryMockRecorder {
	return m.recorder
}

// registerNewValidator mocks base method.
func (m *MockvalidatorRegistry) registerNewValidator(stake uint64) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "registerNewValidator", stake)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// registerNewValidator indicates an expected call of registerNewValidator.
func (mr *MockvalidatorRegistryMockRecorder) registerNewValidator(stake any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "registerNewValidator", reflect.TypeOf((*MockvalidatorRegistry)(nil).registerNewValidator), stake)
}

// unregisterValidator mocks base method.
func (m *MockvalidatorRegistry) unregisterValidator(validatorId int, stake uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "unregisterValidator", validatorId, stake)
	ret0, _ := ret[0].(error)
	return ret0
}

// unregisterValidator indicates an expected call of unregisterValidator.
func (mr *MockvalidatorRegistryMockRecorder) unregisterValidator(validatorId, stake any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "unregisterValidator", reflect.TypeOf((*MockvalidatorRegistry)(nil).unregisterValidator), validatorId, stake)
}
