// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/0xsoniclabs/norma/driver/docker (interfaces: DockerNetwork)
//
// Generated by this command:
//
//	mockgen -destination network_mock.go -package docker . DockerNetwork
//

// Package docker is a generated GoMock package.
package docker

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockDockerNetwork is a mock of DockerNetwork interface.
type MockDockerNetwork struct {
	ctrl     *gomock.Controller
	recorder *MockDockerNetworkMockRecorder
	isgomock struct{}
}

// MockDockerNetworkMockRecorder is the mock recorder for MockDockerNetwork.
type MockDockerNetworkMockRecorder struct {
	mock *MockDockerNetwork
}

// NewMockDockerNetwork creates a new mock instance.
func NewMockDockerNetwork(ctrl *gomock.Controller) *MockDockerNetwork {
	mock := &MockDockerNetwork{ctrl: ctrl}
	mock.recorder = &MockDockerNetworkMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDockerNetwork) EXPECT() *MockDockerNetworkMockRecorder {
	return m.recorder
}

// Cleanup mocks base method.
func (m *MockDockerNetwork) Cleanup(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Cleanup", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Cleanup indicates an expected call of Cleanup.
func (mr *MockDockerNetworkMockRecorder) Cleanup(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(
		mr.mock, "Cleanup", reflect.TypeOf((*MockDockerNetwork)(nil).Cleanup), ctx,
	)
}

// ID mocks base method.
func (m *MockDockerNetwork) ID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ID")
	ret0, _ := ret[0].(string)
	return ret0
}

// ID indicates an expected call of ID.
func (mr *MockDockerNetworkMockRecorder) ID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(
		mr.mock, "ID", reflect.TypeOf((*MockDockerNetwork)(nil).ID),
	)
}

// Name mocks base method.
func (m *MockDockerNetwork) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockDockerNetworkMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(
		mr.mock, "Name", reflect.TypeOf((*MockDockerNetwork)(nil).Name),
	)
}
