// Code generated by MockGen. DO NOT EDIT.
// Source: monitoring_data.go
//
// Generated by this command:
//
//	mockgen -source monitoring_data.go -destination monitoring_data_mock.go -package checking
//

// Package checking is a generated GoMock package.
package checking

import (
	reflect "reflect"

	monitoring "github.com/0xsoniclabs/norma/driver/monitoring"
	gomock "go.uber.org/mock/gomock"
)

// MockMonitoringData is a mock of MonitoringData interface.
type MockMonitoringData struct {
	ctrl     *gomock.Controller
	recorder *MockMonitoringDataMockRecorder
	isgomock struct{}
}

// MockMonitoringDataMockRecorder is the mock recorder for MockMonitoringData.
type MockMonitoringDataMockRecorder struct {
	mock *MockMonitoringData
}

// NewMockMonitoringData creates a new mock instance.
func NewMockMonitoringData(ctrl *gomock.Controller) *MockMonitoringData {
	mock := &MockMonitoringData{ctrl: ctrl}
	mock.recorder = &MockMonitoringDataMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMonitoringData) EXPECT() *MockMonitoringDataMockRecorder {
	return m.recorder
}

// GetBlockGasRate mocks base method.
func (m *MockMonitoringData) GetBlockGasRate() monitoring.Series[monitoring.BlockNumber, float64] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBlockGasRate")
	ret0, _ := ret[0].(monitoring.Series[monitoring.BlockNumber, float64])
	return ret0
}

// GetBlockGasRate indicates an expected call of GetBlockGasRate.
func (mr *MockMonitoringDataMockRecorder) GetBlockGasRate() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBlockGasRate", reflect.TypeOf((*MockMonitoringData)(nil).GetBlockGasRate))
}

// GetBlockStatus mocks base method.
func (m *MockMonitoringData) GetBlockStatus(arg0 monitoring.Node) monitoring.Series[monitoring.Time, monitoring.BlockStatus] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBlockStatus", arg0)
	ret0, _ := ret[0].(monitoring.Series[monitoring.Time, monitoring.BlockStatus])
	return ret0
}

// GetBlockStatus indicates an expected call of GetBlockStatus.
func (mr *MockMonitoringDataMockRecorder) GetBlockStatus(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBlockStatus", reflect.TypeOf((*MockMonitoringData)(nil).GetBlockStatus), arg0)
}

// GetNodes mocks base method.
func (m *MockMonitoringData) GetNodes() []monitoring.Node {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNodes")
	ret0, _ := ret[0].([]monitoring.Node)
	return ret0
}

// GetNodes indicates an expected call of GetNodes.
func (mr *MockMonitoringDataMockRecorder) GetNodes() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNodes", reflect.TypeOf((*MockMonitoringData)(nil).GetNodes))
}
