// Code generated by MockGen. DO NOT EDIT.
// Source: driver/network.go
//
// Generated by this command:
//
//	mockgen -source driver/network.go -destination driver/network_mock.go -package driver
//

// Package driver is a generated GoMock package.
package driver

import (
	context "context"
	reflect "reflect"
	time "time"

	rpc "github.com/0xsoniclabs/norma/driver/rpc"
	types "github.com/ethereum/go-ethereum/core/types"
	gomock "go.uber.org/mock/gomock"
)

// MockNetwork is a mock of Network interface.
type MockNetwork struct {
	ctrl     *gomock.Controller
	recorder *MockNetworkMockRecorder
	isgomock struct{}
}

// MockNetworkMockRecorder is the mock recorder for MockNetwork.
type MockNetworkMockRecorder struct {
	mock *MockNetwork
}

// NewMockNetwork creates a new mock instance.
func NewMockNetwork(ctrl *gomock.Controller) *MockNetwork {
	mock := &MockNetwork{ctrl: ctrl}
	mock.recorder = &MockNetworkMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNetwork) EXPECT() *MockNetworkMockRecorder {
	return m.recorder
}

// AdvanceEpoch mocks base method.
func (m *MockNetwork) AdvanceEpoch(ctx context.Context, epochIncrement int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AdvanceEpoch", ctx, epochIncrement)
	ret0, _ := ret[0].(error)
	return ret0
}

// AdvanceEpoch indicates an expected call of AdvanceEpoch.
func (mr *MockNetworkMockRecorder) AdvanceEpoch(ctx, epochIncrement any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AdvanceEpoch", reflect.TypeOf((*MockNetwork)(nil).AdvanceEpoch), ctx, epochIncrement)
}

// ApplyNetworkRules mocks base method.
func (m *MockNetwork) ApplyNetworkRules(ctx context.Context, rules NetworkRules) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApplyNetworkRules", ctx, rules)
	ret0, _ := ret[0].(error)
	return ret0
}

// ApplyNetworkRules indicates an expected call of ApplyNetworkRules.
func (mr *MockNetworkMockRecorder) ApplyNetworkRules(ctx, rules any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApplyNetworkRules", reflect.TypeOf((*MockNetwork)(nil).ApplyNetworkRules), ctx, rules)
}

// CreateApplication mocks base method.
func (m *MockNetwork) CreateApplication(arg0 context.Context, arg1 *ApplicationConfig) (Application, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateApplication", arg0, arg1)
	ret0, _ := ret[0].(Application)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateApplication indicates an expected call of CreateApplication.
func (mr *MockNetworkMockRecorder) CreateApplication(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateApplication", reflect.TypeOf((*MockNetwork)(nil).CreateApplication), arg0, arg1)
}

// CreateNode mocks base method.
func (m *MockNetwork) CreateNode(config *NodeConfig) (Node, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateNode", config)
	ret0, _ := ret[0].(Node)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateNode indicates an expected call of CreateNode.
func (mr *MockNetworkMockRecorder) CreateNode(config any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateNode", reflect.TypeOf((*MockNetwork)(nil).CreateNode), config)
}

// DialRandomRpc mocks base method.
func (m *MockNetwork) DialRandomRpc() (rpc.Client, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DialRandomRpc")
	ret0, _ := ret[0].(rpc.Client)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DialRandomRpc indicates an expected call of DialRandomRpc.
func (mr *MockNetworkMockRecorder) DialRandomRpc() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DialRandomRpc", reflect.TypeOf((*MockNetwork)(nil).DialRandomRpc))
}

// GetActiveApplications mocks base method.
func (m *MockNetwork) GetActiveApplications() []Application {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActiveApplications")
	ret0, _ := ret[0].([]Application)
	return ret0
}

// GetActiveApplications indicates an expected call of GetActiveApplications.
func (mr *MockNetworkMockRecorder) GetActiveApplications() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActiveApplications", reflect.TypeOf((*MockNetwork)(nil).GetActiveApplications))
}

// GetActiveNodes mocks base method.
func (m *MockNetwork) GetActiveNodes() []Node {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActiveNodes")
	ret0, _ := ret[0].([]Node)
	return ret0
}

// GetActiveNodes indicates an expected call of GetActiveNodes.
func (mr *MockNetworkMockRecorder) GetActiveNodes() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActiveNodes", reflect.TypeOf((*MockNetwork)(nil).GetActiveNodes))
}

// ReconnectNode mocks base method.
func (m *MockNetwork) ReconnectNode(ctx context.Context, node Node) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReconnectNode", ctx, node)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReconnectNode indicates an expected call of ReconnectNode.
func (mr *MockNetworkMockRecorder) ReconnectNode(ctx, node any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReconnectNode", reflect.TypeOf((*MockNetwork)(nil).ReconnectNode), ctx, node)
}

// RegisterListener mocks base method.
func (m *MockNetwork) RegisterListener(arg0 NetworkListener) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RegisterListener", arg0)
}

// RegisterListener indicates an expected call of RegisterListener.
func (mr *MockNetworkMockRecorder) RegisterListener(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterListener", reflect.TypeOf((*MockNetwork)(nil).RegisterListener), arg0)
}

// RegisterTransactionObserver mocks base method.
func (m *MockNetwork) RegisterTransactionObserver(arg0 TransactionObserver) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RegisterTransactionObserver", arg0)
}

// RegisterTransactionObserver indicates an expected call of RegisterTransactionObserver.
func (mr *MockNetworkMockRecorder) RegisterTransactionObserver(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterTransactionObserver", reflect.TypeOf((*MockNetwork)(nil).RegisterTransactionObserver), arg0)
}

// RemoveNode mocks base method.
func (m *MockNetwork) RemoveNode(arg0 Node) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveNode", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveNode indicates an expected call of RemoveNode.
func (mr *MockNetworkMockRecorder) RemoveNode(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveNode", reflect.TypeOf((*MockNetwork)(nil).RemoveNode), arg0)
}

// ResumeNode mocks base method.
func (m *MockNetwork) ResumeNode(node Node) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ResumeNode", node)
}

// ResumeNode indicates an expected call of ResumeNode.
func (mr *MockNetworkMockRecorder) ResumeNode(node any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResumeNode", reflect.TypeOf((*MockNetwork)(nil).ResumeNode), node)
}

// SendTransaction mocks base method.
func (m *MockNetwork) SendTransaction(tx *types.Transaction, source TransactionSource) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SendTransaction", tx, source)
}

// SendTransaction indicates an expected call of SendTransaction.
func (mr *MockNetworkMockRecorder) SendTransaction(tx, source any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendTransaction", reflect.TypeOf((*MockNetwork)(nil).SendTransaction), tx, source)
}

// SendTransactionTo mocks base method.
func (m *MockNetwork) SendTransactionTo(label string, tx *types.Transaction, source TransactionSource) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SendTransactionTo", label, tx, source)
}

// SendTransactionTo indicates an expected call of SendTransactionTo.
func (mr *MockNetworkMockRecorder) SendTransactionTo(label, tx, source any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendTransactionTo", reflect.TypeOf((*MockNetwork)(nil).SendTransactionTo), label, tx, source)
}

// Shutdown mocks base method.
func (m *MockNetwork) Shutdown() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Shutdown")
	ret0, _ := ret[0].(error)
	return ret0
}

// Shutdown indicates an expected call of Shutdown.
func (mr *MockNetworkMockRecorder) Shutdown() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Shutdown", reflect.TypeOf((*MockNetwork)(nil).Shutdown))
}

// SuspendNode mocks base method.
func (m *MockNetwork) SuspendNode(node Node) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SuspendNode", node)
}

// SuspendNode indicates an expected call of SuspendNode.
func (mr *MockNetworkMockRecorder) SuspendNode(node any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SuspendNode", reflect.TypeOf((*MockNetwork)(nil).SuspendNode), node)
}

// UnregisterListener mocks base method.
func (m *MockNetwork) UnregisterListener(arg0 NetworkListener) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "UnregisterListener", arg0)
}

// UnregisterListener indicates an expected call of UnregisterListener.
func (mr *MockNetworkMockRecorder) UnregisterListener(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnregisterListener", reflect.TypeOf((*MockNetwork)(nil).UnregisterListener), arg0)
}

// WaitForEpochChange mocks base method.
func (m *MockNetwork) WaitForEpochChange(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WaitForEpochChange", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// WaitForEpochChange indicates an expected call of WaitForEpochChange.
func (mr *MockNetworkMockRecorder) WaitForEpochChange(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WaitForEpochChange", reflect.TypeOf((*MockNetwork)(nil).WaitForEpochChange), ctx)
}

// MockNetworkListener is a mock of NetworkListener interface.
type MockNetworkListener struct {
	ctrl     *gomock.Controller
	recorder *MockNetworkListenerMockRecorder
	isgomock struct{}
}

// MockNetworkListenerMockRecorder is the mock recorder for MockNetworkListener.
type MockNetworkListenerMockRecorder struct {
	mock *MockNetworkListener
}

// NewMockNetworkListener creates a new mock instance.
func NewMockNetworkListener(ctrl *gomock.Controller) *MockNetworkListener {
	mock := &MockNetworkListener{ctrl: ctrl}
	mock.recorder = &MockNetworkListenerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNetworkListener) EXPECT() *MockNetworkListenerMockRecorder {
	return m.recorder
}

// AfterApplicationCreation mocks base method.
func (m *MockNetworkListener) AfterApplicationCreation(arg0 Application) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AfterApplicationCreation", arg0)
}

// AfterApplicationCreation indicates an expected call of AfterApplicationCreation.
func (mr *MockNetworkListenerMockRecorder) AfterApplicationCreation(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AfterApplicationCreation", reflect.TypeOf((*MockNetworkListener)(nil).AfterApplicationCreation), arg0)
}

// AfterNodeCreation mocks base method.
func (m *MockNetworkListener) AfterNodeCreation(arg0 Node) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AfterNodeCreation", arg0)
}

// AfterNodeCreation indicates an expected call of AfterNodeCreation.
func (mr *MockNetworkListenerMockRecorder) AfterNodeCreation(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AfterNodeCreation", reflect.TypeOf((*MockNetworkListener)(nil).AfterNodeCreation), arg0)
}

// BeforeNodeRemoval mocks base method.
func (m *MockNetworkListener) BeforeNodeRemoval(arg0 Node) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "BeforeNodeRemoval", arg0)
}

// BeforeNodeRemoval indicates an expected call of BeforeNodeRemoval.
func (mr *MockNetworkListenerMockRecorder) BeforeNodeRemoval(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BeforeNodeRemoval", reflect.TypeOf((*MockNetworkListener)(nil).BeforeNodeRemoval), arg0)
}

// MockTransactionObserver is a mock of TransactionObserver interface.
type MockTransactionObserver struct {
	ctrl     *gomock.Controller
	recorder *MockTransactionObserverMockRecorder
	isgomock struct{}
}

// MockTransactionObserverMockRecorder is the mock recorder for MockTransactionObserver.
type MockTransactionObserverMockRecorder struct {
	mock *MockTransactionObserver
}

// NewMockTransactionObserver creates a new mock instance.
func NewMockTransactionObserver(ctrl *gomock.Controller) *MockTransactionObserver {
	mock := &MockTransactionObserver{ctrl: ctrl}
	mock.recorder = &MockTransactionObserverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTransactionObserver) EXPECT() *MockTransactionObserverMockRecorder {
	return m.recorder
}

// OnTransactionSubmitted mocks base method.
func (m *MockTransactionObserver) OnTransactionSubmitted(source TransactionSource, tx *types.Transaction, at time.Time, err error) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "OnTransactionSubmitted", source, tx, at, err)
}

// OnTransactionSubmitted indicates an expected call of OnTransactionSubmitted.
func (mr *MockTransactionObserverMockRecorder) OnTransactionSubmitted(source, tx, at, err any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnTransactionSubmitted", reflect.TypeOf((*MockTransactionObserver)(nil).OnTransactionSubmitted), source, tx, at, err)
}
