// Code generated by MockGen. DO NOT EDIT.
// Source: monitor.go
//
// Generated by this command:
//
//	mockgen -source monitor.go -destination monitor_data_mock.go -package monitoring
//

// Package monitoring is a generated GoMock package.
package monitoring

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockMonitoringBlockStatus is a mock of MonitoringBlockStatus interface.
type MockMonitoringBlockStatus struct {
	ctrl     *gomock.Controller
	recorder *MockMonitoringBlockStatusMockRecorder
	isgomock struct{}
}

// MockMonitoringBlockStatusMockRecorder is the mock recorder for MockMonitoringBlockStatus.
type MockMonitoringBlockStatusMockRecorder struct {
	mock *MockMonitoringBlockStatus
}

// NewMockMonitoringBlockStatus creates a new mock instance.
func NewMockMonitoringBlockStatus(ctrl *gomock.Controller) *MockMonitoringBlockStatus {
	mock := &MockMonitoringBlockStatus{ctrl: ctrl}
	mock.recorder = &MockMonitoringBlockStatusMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMonitoringBlockStatus) EXPECT() *MockMonitoringBlockStatusMockRecorder {
	return m.recorder
}

// GetBlockStatus mocks base method.
func (m *MockMonitoringBlockStatus) GetBlockStatus(arg0 Node) Series[Time, BlockStatus] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBlockStatus", arg0)
	ret0, _ := ret[0].(Series[Time, BlockStatus])
	return ret0
}

// GetBlockStatus indicates an expected call of GetBlockStatus.
func (mr *MockMonitoringBlockStatusMockRecorder) GetBlockStatus(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBlockStatus", reflect.TypeOf((*MockMonitoringBlockStatus)(nil).GetBlockStatus), arg0)
}

// GetNodes mocks base method.
func (m *MockMonitoringBlockStatus) GetNodes() []Node {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNodes")
	ret0, _ := ret[0].([]Node)
	return ret0
}

// GetNodes indicates an expected call of GetNodes.
func (mr *MockMonitoringBlockStatusMockRecorder) GetNodes() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNodes", reflect.TypeOf((*MockMonitoringBlockStatus)(nil).GetNodes))
}
