name: Go

permissions:
  contents: read
  checks: write

on:
  push:
    branches: [ main ]
  pull_request:
    paths:
     - '.github/workflows/go.yml'
     - '.golangci.yml'
     - '**/*.go'
     - 'go.mod'
    branches: [ "**" ]

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: setup go
      uses: actions/setup-go@v5 # Use actions/setup-go to specify the Go version
      with:
        go-version: "1.26.0"
        cache-dependency-path: go/go.sum
    - name: golangci-lint go
      uses: golangci/golangci-lint-action@v9
      with:
        version: v2.12.2
        working-directory: .